k9s:
  liveViewAutoRefresh: true
  refreshRate: 5
  maxConnRetry: 100
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: true
    logoless: true
    crumbsless: true
    noIcons: false
    reactive: true
    skin: aodark
    defaultsToFullScreen: true
  noIcons: false
  skipLatestRevCheck: true
  keepMissingClusters: false
  logger:
    tail: 200
    buffer: 1000
    sinceSeconds: -1
    textWrap: false
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
